"""Read-only assistant adapter for canonical finance source models."""

from __future__ import annotations

from typing import Any, Awaitable, Callable, Optional

from samchat.ar.matching import build_ar_matching_workbench
from samchat.ar.service import build_ar_read_model
from samchat.budgets.service import build_budget_snapshot
from samchat.cashflow.service import build_cashflow_planning_read_model
from samchat.executive.template_reports import (
    build_budget_vs_actual_report,
    build_cashflow_statement_report,
)
from samchat.finance_platform.service import (
    build_finance_platform_snapshot,
    build_finance_source_snapshot,
)


COMMON_SAFETY_LABELS = [
    "read_only",
    "canonical_finance_source",
    "no_legacy_cashflow_route",
    "no_free_sql_recompute",
    "no_financial_effects",
]

AR_SAFETY_LABELS = [
    "matched_collected_is_only_collection_proof",
    "candidate_match_is_evidence_only",
]

CASHFLOW_SAFETY_LABELS = [
    "forecast_is_derived",
    "ar_candidates_not_counted_as_collected",
]

BUDGET_SAFETY_LABELS = [
    "budget_snapshot_read_only",
    "budget_authority_stays_in_presupuestos",
    "artifact_snapshot_must_be_labeled",
]

FINANCE_PLATFORM_SAFETY_LABELS = [
    "finance_platform_read_only",
    "payment_run_is_ap_not_ar",
    "finance_platform_authority_stays_in_module",
]

FINANCE_EXPORT_SAFETY_LABELS = [
    "finance_export_guidance_only",
    "exports_owned_by_source_modules",
    "no_direct_file_generation",
    "legacy_cashflow_not_finance_spine_authority",
]

ALLOWED_INTENTS = (
    "ar.summary",
    "ar.prematching",
    "cashflow.summary",
    "cashflow.statement",
    "budget.snapshot",
    "budget.vs_actual",
    "finance.platform",
    "finance.exports",
)


FinanceSourceCallable = Callable[..., Awaitable[dict[str, Any]]]


def _safety_labels(*extra: str) -> list[str]:
    labels = list(COMMON_SAFETY_LABELS)
    labels.extend(extra)
    return labels


def _source_notes(payload: dict[str, Any], *extra: str) -> list[str]:
    notes = []
    for note in payload.get("source_notes") or []:
        if note not in notes:
            notes.append(str(note))
    for note in extra:
        if note not in notes:
            notes.append(note)
    return notes


def _finance_export_catalog() -> dict[str, Any]:
    return {
        "ok": True,
        "read_only": True,
        "artifact_class": "report_export",
        "exports": [
            {
                "id": "finance_platform_xlsx",
                "owner": "Finance Platform",
                "route": "/admin/finanzas/export.xlsx",
                "artifact_class": "report_export",
                "status": "live",
                "caveat": "Generated by the Finance Platform export route.",
            },
            {
                "id": "budget_review_xlsx",
                "owner": "Presupuestos",
                "route": "/admin/presupuestos/export.xlsx",
                "artifact_class": "report_export",
                "status": "live",
                "caveat": "Budget authority stays in budget versions and services.",
            },
            {
                "id": "budget_concept_catalog_xlsx",
                "owner": "Presupuestos",
                "route": "/admin/presupuestos/conceptos/export.xlsx",
                "artifact_class": "report_export",
                "status": "live",
                "caveat": "Catalog export is not an assistant artifact.",
            },
            {
                "id": "budget_income_mirror_xlsx",
                "owner": "Presupuestos",
                "route_template": (
                    "/admin/presupuestos/torneo/{tournament_key}/ingresos/"
                    "export.xlsx"
                ),
                "artifact_class": "report_export / budget_source_artifact",
                "status": "live",
                "caveat": (
                    "Supports AR expected income, but the workbook is not live "
                    "authority by itself."
                ),
            },
            {
                "id": "assistant_report_export",
                "owner": "Assistant report flow",
                "route": "POST /api/assistant/reports/export",
                "artifact_class": "report_export",
                "status": "live",
                "caveat": "Only for exportable assistant report traces.",
            },
            {
                "id": "accounting_domain_exports",
                "owner": "Accounting/documents/gastos domain",
                "route_family": (
                    "/admin/contabilidad/*, /gastos/*/exportar-*, "
                    "/documentos/*/exportar-*"
                ),
                "artifact_class": "report_export",
                "status": "live/domain-specific",
                "caveat": "Owned by accounting, document, and gastos workflows.",
            },
            {
                "id": "legacy_cashflow_export",
                "owner": "Legacy accounting route",
                "route": "/admin/contabilidad/cash-flow/export.xlsx",
                "artifact_class": "report_export",
                "status": "legacy/reference",
                "caveat": "Not Finance Spine authority.",
            },
        ],
        "source_notes": [
            "finance exports are owned by source modules",
            "assistant_finance_read provides guidance only and does not generate files",
            "legacy cash-flow export is legacy/reference, not Finance Spine authority",
        ],
    }


async def _run_source(
    source: FinanceSourceCallable,
    session: Any,
    *,
    intent: str,
    source_function: str,
    safety_labels: list[str],
    source_note_overrides: list[str],
    source_kwargs: dict[str, Any],
) -> dict[str, Any]:
    payload = await source(session, **source_kwargs)
    return {
        "ok": True,
        "read_only": True,
        "intent": intent,
        "source_function": source_function,
        "payload": payload,
        "source_notes": _source_notes(payload, *source_note_overrides),
        "safety_labels": safety_labels,
    }


async def run_finance_read_adapter(
    session: Any,
    *,
    intent: str,
    budget_version_id: Optional[str] = None,
    tournament_id: Optional[str] = None,
    tournament_code: Optional[str] = None,
    year: Optional[int] = None,
    month: Optional[int] = None,
    horizon_months: int = 3,
    limit: int = 500,
) -> dict[str, Any]:
    """Route approved assistant finance read intents to canonical sources only."""

    if intent == "ar.summary":
        if not budget_version_id:
            return _unsupported_missing_budget_version(intent)
        return await _run_source(
            build_ar_read_model,
            session,
            intent=intent,
            source_function="samchat.ar.service.build_ar_read_model",
            safety_labels=_safety_labels(*AR_SAFETY_LABELS),
            source_note_overrides=[
                "matched_collected is the only AR collection proof",
                "candidate_match is evidence only",
            ],
            source_kwargs={
                "budget_version_id": budget_version_id,
                "tournament_id": tournament_id,
                "tournament_code": tournament_code,
                "limit": limit,
            },
        )

    if intent == "ar.prematching":
        if not budget_version_id:
            return _unsupported_missing_budget_version(intent)
        return await _run_source(
            build_ar_matching_workbench,
            session,
            intent=intent,
            source_function="samchat.ar.matching.build_ar_matching_workbench",
            safety_labels=_safety_labels(*AR_SAFETY_LABELS),
            source_note_overrides=[
                "candidate_match is evidence only",
                "pre-matching has no AR collection authority",
            ],
            source_kwargs={
                "budget_version_id": budget_version_id,
                "tournament_id": tournament_id,
                "tournament_code": tournament_code,
                "year": year,
                "month": month,
                "limit": limit,
            },
        )

    if intent == "cashflow.summary":
        return await _run_source(
            build_cashflow_planning_read_model,
            session,
            intent=intent,
            source_function=(
                "samchat.cashflow.service.build_cashflow_planning_read_model"
            ),
            safety_labels=_safety_labels(*CASHFLOW_SAFETY_LABELS),
            source_note_overrides=[
                "forecast_net is derived",
                "AR candidates are not counted as collected cash",
            ],
            source_kwargs={
                "budget_version_id": budget_version_id,
                "year": year,
                "month": month,
                "horizon_months": horizon_months,
                "limit": limit,
            },
        )

    if intent == "cashflow.statement":
        source_payload = await build_cashflow_planning_read_model(
            session,
            budget_version_id=budget_version_id,
            year=year,
            month=month,
            horizon_months=12,
            limit=limit,
        )
        payload = build_cashflow_statement_report(
            source_payload,
            as_of_year=year,
            as_of_month=month,
        )
        return {
            "ok": True,
            "read_only": True,
            "intent": intent,
            "source_function": (
                "samchat.cashflow.service.build_cashflow_planning_read_model "
                "+ samchat.executive.template_reports."
                "build_cashflow_statement_report"
            ),
            "payload": payload,
            "source_notes": _source_notes(
                payload,
                "cashflow statement template follows uploaded workbook structure",
                "forecast and opening balance caveats must stay visible",
            ),
            "safety_labels": _safety_labels(*CASHFLOW_SAFETY_LABELS),
        }

    if intent == "budget.snapshot":
        payload = await build_budget_snapshot(
            session,
            version_id=budget_version_id,
            tournament_id=tournament_id,
            tournament_slug=tournament_code,
            edition_year=year or 2026,
        )
        source_note_overrides = [
            "budget authority stays in Presupuestos",
            "budget snapshot is read-only",
        ]
        if payload.get("source") != "budget_db":
            source_note_overrides.append(
                "budget snapshot used artifact fallback; verify runtime budget "
                "version before treating it as live DB"
            )
        return {
            "ok": True,
            "read_only": True,
            "intent": intent,
            "source_function": "samchat.budgets.service.build_budget_snapshot",
            "payload": payload,
            "source_notes": _source_notes(payload, *source_note_overrides),
            "safety_labels": _safety_labels(*BUDGET_SAFETY_LABELS),
        }

    if intent == "budget.vs_actual":
        source_payload = await build_budget_snapshot(
            session,
            version_id=budget_version_id,
            tournament_id=tournament_id,
            tournament_slug=tournament_code,
            edition_year=year or 2026,
        )
        payload = build_budget_vs_actual_report(
            source_payload,
            month=month,
            year=year,
        )
        source_note_overrides = [
            "budget vs real template follows uploaded workbook structure",
            "budget authority stays in Presupuestos",
        ]
        if source_payload.get("source") != "budget_db":
            source_note_overrides.append(
                "budget snapshot used artifact fallback; verify runtime budget "
                "version before treating it as live DB"
            )
        return {
            "ok": True,
            "read_only": True,
            "intent": intent,
            "source_function": (
                "samchat.budgets.service.build_budget_snapshot "
                "+ samchat.executive.template_reports."
                "build_budget_vs_actual_report"
            ),
            "payload": payload,
            "source_notes": _source_notes(payload, *source_note_overrides),
            "safety_labels": _safety_labels(*BUDGET_SAFETY_LABELS),
        }

    if intent == "finance.platform":
        source_snapshot = await build_finance_source_snapshot(
            session,
            year=year,
            month=month,
            limit=limit,
        )
        payload = build_finance_platform_snapshot(source_snapshot)
        return {
            "ok": True,
            "read_only": True,
            "intent": intent,
            "source_function": (
                "samchat.finance_platform.service.build_finance_source_snapshot "
                "+ build_finance_platform_snapshot"
            ),
            "payload": payload,
            "source_notes": _source_notes(
                payload,
                "finance platform snapshot is read-only",
                "payment_run is AP/payment-run, not AR collection",
                "finance platform authority stays in Finance Platform",
            ),
            "safety_labels": _safety_labels(*FINANCE_PLATFORM_SAFETY_LABELS),
        }

    if intent == "finance.exports":
        payload = _finance_export_catalog()
        return {
            "ok": True,
            "read_only": True,
            "intent": intent,
            "source_function": (
                "samchat.assistant.finance_read_adapter._finance_export_catalog"
            ),
            "payload": payload,
            "source_notes": _source_notes(
                payload,
                "finance export guidance only",
                "exports are executed by owning modules",
            ),
            "safety_labels": _safety_labels(*FINANCE_EXPORT_SAFETY_LABELS),
        }

    return {
        "ok": False,
        "read_only": True,
        "intent": intent,
        "error": {
            "code": "unsupported_finance_intent",
            "message": "Finance intent is not supported by the read-only adapter.",
        },
        "allowed_intents": list(ALLOWED_INTENTS),
        "safety_labels": _safety_labels(),
    }


def _unsupported_missing_budget_version(intent: str) -> dict[str, Any]:
    return {
        "ok": False,
        "read_only": True,
        "intent": intent,
        "error": {
            "code": "missing_budget_version_id",
            "message": "budget_version_id is required for this finance intent.",
        },
        "allowed_intents": list(ALLOWED_INTENTS),
        "safety_labels": _safety_labels(),
    }
