#!/bin/bash

echo "🚀 Microsoft Azure OCR Setup Script"
echo "===================================="
echo ""

# Check if Azure credentials are set
if [ -z "$AZURE_COMPUTER_VISION_ENDPOINT" ] || [ -z "$AZURE_COMPUTER_VISION_KEY" ]; then
    echo "⚠️  Azure Computer Vision credentials not configured!"
    echo ""
    echo "To use Microsoft OCR, follow these steps:"
    echo ""
    echo "1. Create a free Azure account at: https://azure.microsoft.com/free/"
    echo ""
    echo "2. Create a Computer Vision resource:"
    echo "   - Go to Azure Portal: https://portal.azure.com"
    echo "   - Click 'Create a resource'"
    echo "   - Search for 'Computer Vision'"
    echo "   - Select Free tier (F0) for testing"
    echo "   - Create the resource"
    echo ""
    echo "3. Get your credentials:"
    echo "   - Go to your Computer Vision resource"
    echo "   - Click on 'Keys and Endpoint'"
    echo "   - Copy KEY 1 and Endpoint"
    echo ""
    echo "4. Set environment variables:"
    echo "   export AZURE_COMPUTER_VISION_ENDPOINT='your-endpoint-url'"
    echo "   export AZURE_COMPUTER_VISION_KEY='your-subscription-key'"
    echo ""
    echo "Or add them to your .env file:"
    echo "   AZURE_COMPUTER_VISION_ENDPOINT=your-endpoint-url"
    echo "   AZURE_COMPUTER_VISION_KEY=your-subscription-key"
    echo ""
else
    echo "✅ Azure credentials found!"
    echo "   Endpoint: ${AZURE_COMPUTER_VISION_ENDPOINT}"
    echo "   Key: [HIDDEN]"
    echo ""
    echo "Ready to use Microsoft OCR!"
fi

echo ""
echo "📚 Free Tier Limits:"
echo "   - 5,000 transactions per month"
echo "   - 20 calls per minute"
echo "   - Supports 50+ languages including Spanish"
echo ""
echo "🔧 Usage:"
echo "   python3 microsoft_ocr.py"
echo ""