"""
Services for expense management system.
"""

from .tocino_client import TocinoClient, TocinoAPIError, get_tocino_client, test_connection
from .expense_service import create_expense_from_data, trigger_cfdi_generation, generate_reference_number
from .documento_service import (
    SolicitudPersonalPayload,
    SolicitudValidationError,
    allocate_next_referencia_operaciones,
    allocate_referencia_operaciones_for_empleado,
    build_solicitud_personal_payload,
    build_solicitud_terceros_payload,
    create_solicitud_personal_document,
    create_solicitud_terceros_document,
    empleado_allocates_referencia_operaciones,
    generate_documento_reference_number,
    referencia_operaciones_form_display,
)
from .cuenta_contable_suggester import (
    CuentaContableSuggester,
    CuentaContableSuggestion,
    get_cuenta_suggestion,
    get_cuenta_suggestions_batch,
)
from .expense_accounting_service import (
    build_expense_accounting_preview,
    resolve_counterpart_account,
    summarize_cfdi_tax_components,
)
from .expense_accounting_cleanup_service import (
    CFDICleanupOption,
    build_cleanup_preview,
    list_unassigned_cfdi_options,
    load_cleanup_expenses,
    save_expense_cleanup,
)
from .hospedaje_tax_service import (
    infer_hospedaje_state_from_text,
    normalize_hospedaje_rate,
    normalize_hospedaje_state,
    resolve_hospedaje_local_tax,
)
from .cfdi_matching_service import get_cfdi_matching_overview
from .documento_workflow_service import (
    DocumentoWorkflowError,
    DocumentoWorkflowPermissionError,
    DocumentoWorkflowResult,
    DocumentoWorkflowValidationError,
    promote_solicitudes_ready_for_payment,
    transition_documento_workflow,
)
from .documento_payment_service import (
    DocumentoPagoResult,
    DocumentoPaymentError,
    DocumentoPaymentPermissionError,
    DocumentoPaymentValidationError,
    DocumentoReembolsoResult,
    get_pending_document_payment_overview,
    register_document_payment,
    register_document_reembolso,
)
from .cuenta_settlement_service import (
    CuentaSettlementError,
    CuentaSettlementPermissionError,
    CuentaSettlementResult,
    CuentaSettlementValidationError,
    cancel_cuenta_settlement,
    compute_cuenta_saldo_adjustments,
    register_cuenta_settlement,
)
from .support_ticket_service import (
    AdminTicketSummary,
    SupportTicketError,
    SupportTicketNotFoundError,
    SupportTicketPermissionError,
    SupportTicketValidationError,
    add_ticket_comment,
    create_ticket,
    get_ticket_for_user,
    list_admin_tickets,
    list_my_tickets,
    list_staff_empleados,
    summarize_admin_tickets,
    update_ticket_admin_fields,
)

__all__ = [
    'TocinoClient',
    'TocinoAPIError',
    'get_tocino_client',
    'test_connection',
    'create_expense_from_data',
    'trigger_cfdi_generation',
    'generate_reference_number',
    'SolicitudPersonalPayload',
    'SolicitudValidationError',
    'allocate_next_referencia_operaciones',
    'allocate_referencia_operaciones_for_empleado',
    'empleado_allocates_referencia_operaciones',
    'referencia_operaciones_form_display',
    'build_solicitud_personal_payload',
    'build_solicitud_terceros_payload',
    'create_solicitud_personal_document',
    'create_solicitud_terceros_document',
    'generate_documento_reference_number',
    # Cuenta Contable Suggestion (LEAP_SPEC_3)
    'CuentaContableSuggester',
    'CuentaContableSuggestion',
    'get_cuenta_suggestion',
    'get_cuenta_suggestions_batch',
    'build_expense_accounting_preview',
    'resolve_counterpart_account',
    'summarize_cfdi_tax_components',
    'CFDICleanupOption',
    'build_cleanup_preview',
    'list_unassigned_cfdi_options',
    'load_cleanup_expenses',
    'save_expense_cleanup',
    'infer_hospedaje_state_from_text',
    'normalize_hospedaje_rate',
    'normalize_hospedaje_state',
    'resolve_hospedaje_local_tax',
    'get_cfdi_matching_overview',
    'DocumentoWorkflowError',
    'DocumentoWorkflowPermissionError',
    'DocumentoWorkflowResult',
    'DocumentoWorkflowValidationError',
    'transition_documento_workflow',
    'DocumentoPagoResult',
    'DocumentoPaymentError',
    'DocumentoPaymentPermissionError',
    'DocumentoPaymentValidationError',
    'DocumentoReembolsoResult',
    'get_pending_document_payment_overview',
    'register_document_payment',
    'register_document_reembolso',
    'CuentaSettlementError',
    'CuentaSettlementPermissionError',
    'CuentaSettlementResult',
    'CuentaSettlementValidationError',
    'cancel_cuenta_settlement',
    'compute_cuenta_saldo_adjustments',
    'register_cuenta_settlement',
    # Support tickets
    'AdminTicketSummary',
    'SupportTicketError',
    'SupportTicketNotFoundError',
    'SupportTicketPermissionError',
    'SupportTicketValidationError',
    'add_ticket_comment',
    'create_ticket',
    'get_ticket_for_user',
    'list_admin_tickets',
    'list_my_tickets',
    'list_staff_empleados',
    'summarize_admin_tickets',
    'update_ticket_admin_fields',
]
