#!/usr/bin/env python3
"""Audit or consolidate duplicate budget partidas.

Dry-run is the default. ``--apply`` requires a plan hash generated by this
script and an explicit production confirmation. Recovery snapshot tables are
never modified.
"""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from sqlalchemy import text
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from samchat.budgets.deduplication import (  # noqa: E402
    choose_canonical_budget_concept,
    duplicate_budget_concept_groups,
)

REFERENCE_TABLES = (
    "budget_cfdi_income_links",
    "budget_lines",
    "documentos",
    "expense_reports",
)


def _load_env_file(path: str | None) -> None:
    if not path:
        return
    for raw_line in Path(path).read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, value = line.split("=", 1)
            os.environ.setdefault(key.strip(), value.strip().strip("'\""))


def _database_url() -> str:
    url = (os.getenv("DATABASE_URL") or "").strip()
    if not url:
        raise SystemExit("DATABASE_URL is required")
    return url.replace("postgresql://", "postgresql+asyncpg://", 1)


async def _catalog_rows(session: Any) -> list[dict[str, Any]]:
    result = await session.execute(
        text(
            """
            SELECT bc.id::text, bc.tournament_id::text, bc.tournament_name,
                   bc.concept_name, bc.budget_direction, bc.concept_key,
                   bc.active, bc.source, bc.metadata,
                   bc.cuenta_contable_id::text,
                   cc.codigo AS cuenta_contable_codigo,
                   bc.created_at,
                   (SELECT count(*) FROM budget_cfdi_income_links x
                     WHERE x.budget_concept_id = bc.id)
                   + (SELECT count(*) FROM budget_lines x
                      WHERE x.budget_concept_id = bc.id)
                   + (SELECT count(*) FROM documentos x
                      WHERE x.budget_concept_id = bc.id)
                   + (SELECT count(*) FROM expense_reports x
                      WHERE x.budget_concept_id = bc.id)
                     AS reference_count
            FROM budget_concepts bc
            LEFT JOIN cuentas_contables cc ON cc.id = bc.cuenta_contable_id
            WHERE bc.active = TRUE
            ORDER BY bc.tournament_name, bc.concept_name, bc.created_at, bc.id
            """
        )
    )
    return [dict(row) for row in result.mappings().all()]


def _plan(rows: list[dict[str, Any]]) -> dict[str, Any]:
    operations = []
    for identity, members in duplicate_budget_concept_groups(rows):
        canonical = choose_canonical_budget_concept(members)
        duplicates = [row for row in members if row["id"] != canonical["id"]]
        operations.append(
            {
                "identity": identity,
                "canonical_id": canonical["id"],
                "duplicate_ids": [row["id"] for row in duplicates],
                "reference_count": sum(
                    int(row.get("reference_count") or 0) for row in members
                ),
                "sources": sorted(
                    {str(row.get("source") or "") for row in members}
                ),
            }
        )
    payload = {"operations": operations}
    canonical_json = json.dumps(
        payload, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    )
    return {
        **payload,
        "plan_sha256": hashlib.sha256(canonical_json.encode()).hexdigest(),
    }


async def _apply(
    session: Any,
    plan: dict[str, Any],
    actor: str,
) -> dict[str, int]:
    updated_references = 0
    deactivated = 0
    for operation in plan["operations"]:
        canonical_id = operation["canonical_id"]
        duplicate_ids = operation["duplicate_ids"]
        for table in REFERENCE_TABLES:
            result = await session.execute(
                text(
                    f"UPDATE {table} "
                    "SET budget_concept_id = CAST(:canonical_id AS uuid) "
                    "WHERE budget_concept_id = ANY("
                    "CAST(:duplicate_ids AS uuid[]))"
                ),
                {"canonical_id": canonical_id, "duplicate_ids": duplicate_ids},
            )
            updated_references += int(result.rowcount or 0)
        result = await session.execute(
            text(
                """
                UPDATE budget_concepts
                SET active = FALSE,
                    metadata = COALESCE(metadata, '{}'::jsonb)
                        || CAST(:metadata AS jsonb),
                    updated_at = NOW()
                WHERE id = ANY(CAST(:duplicate_ids AS uuid[]))
                  AND active = TRUE
                """
            ),
            {
                "duplicate_ids": duplicate_ids,
                "metadata": json.dumps(
                    {
                        "consolidated_into": canonical_id,
                        "consolidated_by": actor,
                        "consolidated_at": datetime.now(timezone.utc)
                        .isoformat(),
                    }
                ),
            },
        )
        deactivated += int(result.rowcount or 0)
    return {
        "updated_references": updated_references,
        "deactivated": deactivated,
    }


async def _run(args: argparse.Namespace) -> int:
    _load_env_file(args.env_file)
    engine = create_async_engine(_database_url())
    maker = async_sessionmaker(engine, expire_on_commit=False)
    try:
        async with maker() as session:
            plan = _plan(await _catalog_rows(session))
            receipt: dict[str, Any] = {"apply": args.apply, **plan}
            if not args.apply:
                await session.rollback()
            else:
                if (
                    not args.confirm_production_reconciliation
                    or not args.actor_id
                ):
                    raise SystemExit(
                        "--apply requires --confirm-production-reconciliation "
                        "and --actor-id"
                    )
                if args.expected_plan_sha256 != plan["plan_sha256"]:
                    raise SystemExit(
                        "plan_hash_mismatch; run dry-run again and review "
                        "the receipt"
                    )
                receipt["applied"] = await _apply(session, plan, args.actor_id)
                await session.commit()
            print(
                json.dumps(receipt, ensure_ascii=False, indent=2, default=str)
            )
    finally:
        await engine.dispose()
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--env-file")
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--actor-id")
    parser.add_argument("--expected-plan-sha256")
    parser.add_argument(
        "--confirm-production-reconciliation", action="store_true"
    )
    return asyncio.run(_run(parser.parse_args()))


if __name__ == "__main__":
    raise SystemExit(main())
